title: Schema-GMapify
baseurl: "/schema-gmapify"

date_format: "%Y-%m-%d"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "with_toc_data"]
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-70242125-2
disqus_shortname:

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

exclude:
  - bower.json
  - node_modules

navigation:
  - text: Docs
    url: /
  - text: Demo
    url: /demo.html